### ISSUE TITLE
authenticity of host problem

### ISSUE THREAD

**Issue by joshwalawender** [KeckObservatory/RemoteObserving#32]
There seems to be a problem with the new sshtunnel from the command line strategy.  We get the `authenticity of host ...` query from ssh, but the code get's confused as we can't really answer it.  This also seems to be inconsistent.  I've had two observers test and then connect once successfully, then a second time has this problem.

Logs (did not capture ssh output), see screenshot below.
```
2020-03-20 20:14:22,785 UT - DEBUG: Checking for port 5902 in use: lsof -i -P -n | grep LISTEN | grep ":5902 (LISTEN)" | grep -v grep
2020-03-20 20:14:22,943 UT - DEBUG: Checking for port 5902 in use: lsof -i -P -n | grep LISTEN | grep ":5902 (LISTEN)" | grep -v grep
2020-03-20 20:14:23,107 UT - DEBUG: Checking for port 5902 in use: lsof -i -P -n | grep LISTEN | grep ":5902 (LISTEN)" | grep -v grep
2020-03-20 20:14:23,277 UT - ERROR: Failed to open SSH tunnel for kvnc@kcwi.keck.hawaii.edu:5930
2020-03-20 20:14:23,278 UT - DEBUG: Traceback (most recent call last):
  File "keck_vnc_launcher.py", line 278, in start_vnc_session
    session_name=session_name)
  File "keck_vnc_launcher.py", line 569, in open_ssh_tunnel
    raise RuntimeError('ssh tunnel failed to open after 5 seconds')
RuntimeError: ssh tunnel failed to open after 5 seconds

2020-03-20 20:14:23,278 UT - INFO: Opening VNCviewer for 'control2'
2020-03-20 20:14:23,279 UT - DEBUG: Checking for port 5903 in use: lsof -i -P -n | grep LISTEN | grep ":5903 (LISTEN)" | grep -v grep
2020-03-20 20:14:23,347 UT - INFO: Opening SSH tunnel for kvnc@kcwi.keck.hawaii.edu:5931 on local port 5903.
2020-03-20 20:14:23,348 UT - DEBUG: ssh command: ssh -l kvnc -L 5903:localhost:5931 -N -T kcwi.keck.hawaii.edu -i /Users/karin/.ssh/id_rsa
2020-03-20 20:14:23,353 UT - DEBUG: Checking for port 5903 in use: lsof -i -P -n | grep LISTEN | grep ":5903 (LISTEN)" | grep -v grep
2020-03-20 20:14:23,557 UT - DEBUG: Checking for port 5903 in use: lsof -i -P -n | grep LISTEN | grep ":5903 (LISTEN)" | grep -v grep
2020-03-20 20:14:23,741 UT - DEBUG: Checking for port 5903 in use: lsof -i -P -n | grep LISTEN | grep ":5903 (LISTEN)" | grep -v grep
2020-03-20 20:14:23,907 UT - DEBUG: Checking for port 5903 in use: lsof -i -P -n | grep LISTEN | grep ":5903 (LISTEN)" | grep -v grep
2020-03-20 20:14:24,077 UT - DEBUG: Checking for port 5903 in use: lsof -i -P -n | grep LISTEN | grep ":5903 (LISTEN)" | grep -v grep
2020-03-20 20:14:24,255 UT - DEBUG: Checking for port 5903 in use: lsof -i -P -n | grep LISTEN | grep ":5903 (LISTEN)" | grep -v grep
2020-03-20 20:14:24,313 UT - DEBUG: Port 5903 is in use.
2020-03-20 20:14:24,326 UT - DEBUG: VNC viewer command: ['/Applications/RealVNC/VNC Viewer.app/Contents/MacOS/vncviewer', '-Shared', '-FullColor', '-PreferredEncoding=ZRLE', '-AutoSelect=0', 'localhost:5903']
2020-03-20 20:14:24,382 UT - INFO: Opening VNCviewer for 'telstatus'
2020-03-20 20:14:24,383 UT - DEBUG: Checking for port 5904 in use: lsof -i -P -n | grep LISTEN | grep ":5904 (LISTEN)" | grep -v grep
2020-03-20 20:14:24,536 UT - INFO: Opening SSH tunnel for kvnc@kcwi.keck.hawaii.edu:5932 on local port 5904.
2020-03-20 20:14:24,537 UT - DEBUG: ssh command: ssh -l kvnc -L 5904:localhost:5932 -N -T kcwi.keck.hawaii.edu -i /Users/karin/.ssh/id_rsa
2020-03-20 20:14:24,542 UT - DEBUG: Checking for port 5904 in use: lsof -i -P -n | grep LISTEN | grep ":5904 (LISTEN)" | grep -v grep
2020-03-20 20:14:24,866 UT - DEBUG: Checking for port 5904 in use: lsof -i -P -n | grep LISTEN | grep ":5904 (LISTEN)" | grep -v grep
2020-03-20 20:14:25,123 UT - DEBUG: Checking for port 5904 in use: lsof -i -P -n | grep LISTEN | grep ":5904 (LISTEN)" | grep -v grep
2020-03-20 20:14:25,381 UT - DEBUG: Checking for port 5904 in use: lsof -i -P -n | grep LISTEN | grep ":5904 (LISTEN)" | grep -v grep
2020-03-20 20:14:25,652 UT - DEBUG: Checking for port 5904 in use: lsof -i -P -n | grep LISTEN | grep ":5904 (LISTEN)" | grep -v grep
2020-03-20 20:14:25,774 UT - DEBUG: Port 5904 is in use.
2020-03-20 20:14:25,775 UT - DEBUG: VNC viewer command: ['/Applications/RealVNC/VNC Viewer.app/Contents/MacOS/vncviewer', '-Shared', '-FullColor', '-PreferredEncoding=ZRLE', '-AutoSelect=0', 'localhost:5904']
2020-03-20 20:14:25,830 UT - DEBUG: Checking for port 5905 in use: lsof -i -P -n | grep LISTEN | grep ":5905 (LISTEN)" | grep -v grep
2020-03-20 20:14:25,970 UT - INFO: Opening SSH tunnel for kvnc@kcwi.keck.hawaii.edu:9798 on local port 5905.
2020-03-20 20:14:25,971 UT - DEBUG: ssh command: ssh -l kvnc -L 5905:localhost:9798 -N -T kcwi.keck.hawaii.edu -i /Users/karin/.ssh/id_rsa
2020-03-20 20:14:25,974 UT - DEBUG: Checking for port 5905 in use: lsof -i -P -n | grep LISTEN | grep ":5905 (LISTEN)" | grep -v grep
2020-03-20 20:14:26,214 UT - DEBUG: Checking for port 5905 in use: lsof -i -P -n | grep LISTEN | grep ":5905 (LISTEN)" | grep -v grep
2020-03-20 20:14:26,565 UT - DEBUG: Checking for port 5905 in use: lsof -i -P -n | grep LISTEN | grep ":5905 (LISTEN)" | grep -v grep
2020-03-20 20:14:26,815 UT - DEBUG: Checking for port 5905 in use: lsof -i -P -n | grep LISTEN | grep ":5905 (LISTEN)" | grep -v grep
2020-03-20 20:14:27,067 UT - DEBUG: Checking for port 5905 in use: lsof -i -P -n | grep LISTEN | grep ":5905 (LISTEN)" | grep -v grep
2020-03-20 20:14:27,149 UT - DEBUG: Port 5905 is in use.
2020-03-20 20:14:27,150 UT - INFO: Starting soundplayer: server=localhost, instrument=kcwi
2020-03-20 20:14:27,150 UT - DEBUG: Checking for existing soundplay process: ps -elf | grep soundplay | grep "localhost:5905" | grep kcwi | grep -v grep
2020-03-20 20:14:27,410 UT - DEBUG: Soundplay cmd: ['/Users/karin/RemoteObserving/soundplayer/soundplay-107050-8.6.3-macosx10.5-ix86+x86_64', '-s', 'localhost:5905', '-T', 'kcwi', '-px', '/usr/bin/afplay -v 1 %s']
2020-03-20 20:15:19,827 UT - INFO: Recieved command "es"
2020-03-20 20:15:19,827 UT - ERROR: Unrecognized command: "es"
2020-03-20 20:15:32,957 UT - INFO: Recieved command "yes"
2020-03-20 20:15:32,959 UT - ERROR: Unrecognized command: "yes"
2020-03-20 20:15:41,020 UT - INFO: Recieved command "no"
2020-03-20 20:15:41,021 UT - ERROR: Unrecognized command: "no"
2020-03-20 20:16:09,476 UT - INFO: App exit
2020-03-20 20:16:09,476 UT - INFO: Terminating soundplay process...
2020-03-20 20:16:09,477 UT - INFO:  Closing SSH tunnel for port 5903, control2 on kvnc@kcwi.keck.hawaii.edu:5931
2020-03-20 20:16:09,479 UT - INFO:  Closing SSH tunnel for port 5904, telstatus on kvnc@kcwi.keck.hawaii.edu:5932
2020-03-20 20:16:09,479 UT - INFO:  Closing SSH tunnel for port 5905, unknown on kvnc@kcwi.keck.hawaii.edu:9798
2020-03-20 20:16:09,480 UT - INFO: Signing off of firewall authentication
2020-03-20 20:16:10,086 UT - INFO: User was signed off from all services
2020-03-20 20:16:10,086 UT - INFO: Terminating all VNC sessions.
2020-03-20 20:16:10,087 UT - DEBUG: terminating VNC process: ['/Applications/RealVNC/VNC Viewer.app/Contents/MacOS/vncviewer', '-Shared', '-FullColor', '-PreferredEncoding=ZRLE', '-AutoSelect=0', 'localhost:5904']
2020-03-20 20:16:10,087 UT - DEBUG: terminating VNC process: ['/Applications/RealVNC/VNC Viewer.app/Contents/MacOS/vncviewer', '-Shared', '-FullColor', '-PreferredEncoding=ZRLE', '-AutoSelect=0', 'localhost:5903']
2020-03-20 20:16:10,087 UT - INFO: EXITING APP

```

<img width="1038" alt="Screen Shot 2020-03-20 at 10 21 24 AM" src="https://user-images.githubusercontent.com/4873464/77203670-0ed91300-6a95-11ea-83bf-250f56ed10f6.png">

**Comment by klanclos** [comment]
Hmm. Hmmmmm.

**Comment by klanclos** [comment]
Similar to the fix for the host key exchange we can add this option on the command line:

    -oStrictHostKeyChecking=no

**Comment by joshjriley** [comment]
Not saying we can't solve this, but if the sshtunnel module has solved a lot of these and perhaps other unforseen problems, using the module might outweigh getting around the conda dependency.

**Comment by klanclos** [comment]
I'm willing to pay a modest price if it gets rid of an exotic dependency.
